site_name: Bastalon
theme: 
  name: material


nav:
  - Indice: index.md
  - Descrizione del progetto: descrizione_del_progetto.md
  - Requisiti: requisiti.md
  - Validazione: validazione.md
  - Manutenzione: manutenzione.md